CREATE TABLE TREATMENT_ROOMS
(
    ID   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME varchar(256) UNIQUE                          NOT NULL
);

INSERT INTO TREATMENT_ROOMS(NAME)
VALUES ('UNSPECIFIED');

ALTER TABLE visits
    ADD COLUMN TREATMENT_ROOM_ID INT NOT NULL default 1;

ALTER TABLE visits
    ADD CONSTRAINT fk_TREATMENT_ROOM
        FOREIGN KEY (TREATMENT_ROOM_ID)
            REFERENCES TREATMENT_ROOMS (ID);